# Generated by Django 5.0.6 on 2024-05-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(null=True, verbose_name='Ссылка на файл с графиком')),
                ('green', models.CharField(max_length=400, null=True, verbose_name='Зелёный в RGB')),
                ('red', models.CharField(max_length=400, null=True, verbose_name='Красный в RGB')),
                ('str_number_for_day', models.IntegerField(null=True, verbose_name='Номер строки с числом')),
                ('rocket_token', models.CharField(max_length=400, null=True, verbose_name='Rocket.chat Token')),
                ('rocket_user_id', models.CharField(max_length=100, null=True, verbose_name='Rocket.chat User ID')),
                ('rocket_url', models.URLField(null=True, verbose_name='Rocket.chat url')),
                ('rocket_channel', models.CharField(max_length=100, null=True, verbose_name='Название канала или группы Rocket.chat')),
            ],
            options={
                'verbose_name': 'Настройки бота',
            },
        ),
    ]
