# Generated by Django 5.0.6 on 2024-05-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsetting',
            options={'verbose_name': 'Настройки бота', 'verbose_name_plural': 'Настройки бота'},
        ),
    ]
