# Generated by Django 5.0.6 on 2024-07-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_niconsurname'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='blue',
            field=models.CharField(max_length=400, null=True, verbose_name='Синий в RGB'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='interval',
            field=models.IntegerField(null=True, verbose_name='Интервал для отпуска'),
        ),
    ]
