# Generated by Django 5.1.5 on 2025-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_botsetting_blue_botsetting_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='col_number_for_nic',
            field=models.CharField(max_length=2, null=True, verbose_name='Буква столбца с ФИО(регистр не важен)'),
        ),
    ]
