version: '3'
services:

  redis:
    image: redis
    environment:
      - TZ=Europe/Moscow

  api:
    build:
      context: .
    ports:
      - "8000:8000"
    tty: true
    environment:
      - TZ=Europe/Moscow
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./db:/app/db
    depends_on:
      - redis

  celery:
    build:
      context: .
    tty: true
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./db:/app/db
    command: celery -A config worker -l INFO
    depends_on:
      - api

  celery-beat:
    build:
      context: .
    tty: true
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./db:/app/db
    command: celery -A config beat -l INFO
    depends_on:
      - celery

  flower:
    build:
      context: .
    container_name: flower_app
    command: celery -A config flower -l INFO
    volumes:
      - ./db:/app/db
    depends_on:
      - celery-beat
    ports:
      - "8888:5555"